### ISSUE TITLE
Shell command errors occassionally contain bad characters for influx

### ISSUE THREAD

**Issue by hagertnl** [olcf/olcf-test-harness#47]
The `test_mkdir_shell_error` unit test of harness unit tests replicates this. Example 1 - use of `mkdir` when the directory already exists:
Made a directory. Trying to make it again
mkdir: cannot create directory ‘./a’: File exists

Results in a log message of:
Time: 2022-07-20 12:36:39,593
Logger: status_file.harness_unit_tests__test_mkdir_shell_error
Loglevel: ERROR
Message:
An error occurred 'latin-1' codec can't encode character '\u2018' in position 1555: Body ('‘') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

**Comment by hagertnl** [comment]
I am unable to reproduce this error at this time.

**Comment by hagertnl** [comment]
The rocHPL build is now producting this error:
```
The following exception occurred while logging an event to https://...: 'latin-1' codec can't encode character '\u2018' in position 10412: Body ('‘') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8..
```

**Comment by hagertnl** [comment]
I commented out the try/catch to get a more detailed stack trace:
```
Traceback (most recent call last):
  File "/sw/acceptance/olcf-test-harness-dev/harness/bin/test_harness_driver.py", line 536, in <module>
    exit_code = test_harness_driver()
  File "/sw/acceptance/olcf-test-harness-dev/harness/bin/test_harness_driver.py", line 496, in test_harness_driver
    Vargs.separate_build_stdio)
  File "/sw/acceptance/olcf-test-harness-dev/harness/bin/test_harness_driver.py", line 185, in auto_generated_scripts
    jstatus.log_event(status_file.StatusFile.EVENT_BUILD_END, build_exit_value)
  File "/sw/acceptance/olcf-test-harness-dev/harness/libraries/status_file.py", line 356, in log_event
    event_type, event_subtype, str(event_value))
  File "/sw/acceptance/olcf-test-harness-dev/harness/libraries/status_file.py", line 576, in __log_event
    self.__db_logger.log_event(status_info_dict)
  File "/sw/acceptance/olcf-test-harness-dev/harness/libraries/rgt_database_loggers/rgt_database_logger.py", line 76, in log_event
    if not backend.send_event(event_dict):
  File "/sw/acceptance/olcf-test-harness-dev/harness/libraries/rgt_database_loggers/db_backends/rgt_influxdb.py", line 220, in send_event
    return self._send_message(self._get_write_url(), influx_event_record_string, headers)
  File "/sw/acceptance/olcf-test-harness-dev/harness/libraries/rgt_database_loggers/db_backends/rgt_influxdb.py", line 485, in _send_message
    r = requests.post(full_url, data=message, headers=headers)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 678, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 393, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1291, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1336, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib64/python3.6/http/client.py", line 175, in _encode
    (name.title(), data[err.start:err.end], name)) from None
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 10560: Body ('‘') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

**Comment by hagertnl** [comment]
The last piece of that trace is from this function:
```
def _encode(data, name='data'):
    """Call data.encode("latin-1") but show a better error message."""
    try:
        return data.encode("latin-1")
    except UnicodeEncodeError as err:
        raise UnicodeEncodeError(
            err.encoding,
            err.object,
            err.start,
            err.end,
            "%s (%.20r) is not valid Latin-1. Use %s.encode('utf-8') "
            "if you want to send it encoded in UTF-8." %
            (name.title(), data[err.start:err.end], name)) from None
```

**Comment by hagertnl** [comment]
The resolution is to pre-encode the data and send it to `requests.post` as a byte array already. Here is the patch I will push shortly:
```
diff --git a/harness/libraries/rgt_database_loggers/db_backends/rgt_influxdb.py b/harness/libraries/rgt_database_loggers/db_backends/rgt_influxdb.py
index adb725e..cfc5328 100644
--- a/harness/libraries/rgt_database_loggers/db_backends/rgt_influxdb.py
+++ b/harness/libraries/rgt_database_loggers/db_backends/rgt_influxdb.py
@@ -482,7 +482,7 @@ class InfluxDBLogger(BaseDBLogger):

         self.__logger.doDebugLogging(f"Sending message to InfluxDB: {message}")
         # We do not catch the exception here -- it will be caught in the database manager class
-        r = requests.post(full_url, data=message, headers=headers)
+        r = requests.post(full_url, data=message.encode('utf-8'), headers=headers)

         if r.status_code == 200 or r.status_code == 204:
             self.__logger.doDebugLogging(f"Logged to InfluxDB successfully ({r.status_code}, {r.reason}): {message}")
```
