### ISSUE TITLE
influx_logged file seems to exist before it should in test

### ISSUE THREAD

**Issue by hagertnl** [olcf/olcf-test-harness#64]
I ran into an instance of this today while testing. The harness terminated in the check step with
```
Traceback (most recent call last):
  File "/sw/acceptance/olcf-test-harness-09-15-2022/harness/bin/test_harness_driver.py", line 527, in <module>
    test_harness_driver()
  File "/sw/acceptance/olcf-test-harness-09-15-2022/harness/bin/test_harness_driver.py", line 487, in test_harness_driver
    Vargs.separate_build_stdio)
  File "/sw/acceptance/olcf-test-harness-09-15-2022/harness/bin/test_harness_driver.py", line 294, in auto_generated_scripts
    influx_reported = mymachine.log_to_influx()
  File "/sw/acceptance/olcf-test-harness-09-15-2022/harness/machine_types/base_machine.py", line 424, in log_to_influx
    exit_status = self._log_to_influx()
  File "/sw/acceptance/olcf-test-harness-09-15-2022/harness/machine_types/base_machine.py", line 507, in _log_to_influx
    return self.apptest._log_to_influx(self.apptest.get_harness_id())
  File "/sw/acceptance/olcf-test-harness-09-15-2022/harness/libraries/apptest.py", line 828, in _log_to_influx
    os.mknod('.influx_logged')
FileExistsError: [Errno 17] File exists
```
I'm not sure how this happened, but in the meantime, I would like to wrap the `os.mknod` in a conditional checking if the file exists first. If it does exist, then print useful information from inside the code, but terminate normally. This *should* never be triggered.

**Comment by hagertnl** [comment]
My current thinking is that in the new style of logging, where the node health check and metrics are logged, somewhere along the way, the current path is being changed to SCRIPTS_DIR, and the .influx_logged file is being created there instead of RESULTS_DIR. Tracking now.

**Comment by hagertnl** [comment]
Found problematic code. Function local_send_to_influx in apptest.py:670 uses `os.chdir(currentdir)` when InfluxDB is not reachable. This puts us back in SCRIPTSDIR without aborting the metrics checking function. Working to resolve now, will open PR soon.
