### ISSUE TITLE
Tests running in tandem have race condition on latest link and may crash

### ISSUE THREAD

**Issue by hagertnl** [olcf/olcf-test-harness#67]
I was running 2 runs of the same test, launching one after another. The first one crashed while running either the log_binary_execution_time or check_executable_driver with this error:

```
HARNESS ERROR: Failed to create symlink /autofs/nccs-svm1_proj/stf016/hagertnl/harness/frontier/applications/harness_unit_tests/test_successful_run/Status/latest to /autofs/nccs-svm1_proj/stf016/hagertnl/harness/frontier/applications/harness_unit_tests/test_successful_run/Status/1663943746.2020762.
Traceback (most recent call last):
  File "/sw/acceptance/olcf-test-harness-09-15-2022/harness/bin/test_harness_driver.py", line 527, in <module>
    test_harness_driver()
  File "/sw/acceptance/olcf-test-harness-09-15-2022/harness/bin/test_harness_driver.py", line 435, in test_harness_driver
    ra_dir = apptest.create_test_runarchive()
  File "/sw/acceptance/olcf-test-harness-09-15-2022/harness/libraries/layout_of_apps_directory.py", line 239, in create_test_runarchive
    os.unlink(latest_lnk)
FileNotFoundError: [Errno 2] No such file or directory: '/autofs/nccs-svm1_proj/stf016/hagertnl/harness/frontier/applications/harness_unit_tests/test_successful_run/Run_Archive/latest'
```

**Comment by hagertnl** [comment]
Likely root cause of #54
